package com.gestaocis.backend.utils.enums;

public enum Specialty {
  SPECIALTY_GENERAL_PRACTITIONER,
  SPECIALTY_PSYCHOLOGY,
  SPECIALTY_PHYSIOTHERAPY,
  SPECIALTY_NUTRITION,
  SPECIALTY_PSYCHIATRY,
  SPECIALTY_ACUPUNTURE,
  SPECIALTY_MASSAGE,
  SPECIALTY_PSYCHOPEDAGOGY,
  SPECIALTY_SPEECH_THERAPY,
  SPECIALTY_FACE_BODY_AESTHETICS;
}
