version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: root
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5432:5432"


volumes:
  database: